# Generated by Django 5.2.11 on 2026-02-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novatech', '0002_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
